# Data Loading and Cleaning

In [30]:
import pandas as pd

df = pd.read_csv(r"D:\personal Projects\Agentic AI\Reaestate Agent 3\Data\Raw\nobroker_slow_scroll.csv")
df.head()

,full_title,society_name,rent,area_sqft,furnishing,apartment_type,preferred_tenants,link
0,2 BHK Apartment In Arihant Abode for Rent In ...,Arihant Abode,24000,1055,Fully Furnished,2 BHK,"Female, Family",https://www.nobroker.in/property/2-bhk-apartme...
1,2 BHK Apartment In Nimbus Express Park View 2 ...,Nimbus Express Park View 2,31000,1114,Fully Furnished,2 BHK,"Female, Family, Company",https://www.nobroker.in/property/2-bhk-apartme...
2,"2 BHK Apartment In Panchsheel Greens, Sector 1...","Panchsheel Greens, Sector 16 B",20000,975,Fully Furnished,2 BHK,Male,https://www.nobroker.in/property/2-bhk-apartme...
3,2 BHK Apartment In Ace Divino for Rent In Sec...,Supertech Eco Village22 ApartmentsView,26000,1000,Fully Furnished,2 BHK,Male,https://www.nobroker.in/property/2-bhk-apartme...
4,1 BHK Apartment In Supertech Czar for Rent In...,supertech czar,16000,535,Fully Furnished,1 BHK,Male,https://www.nobroker.in/property/1-bhk-apartme...

In [31]:
df.isnull().sum()

full_title              0
society_name          906
rent                    0
area_sqft               0
furnishing           1357
apartment_type          0
preferred_tenants       0
link                    0
dtype: int64

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1802 entries, 0 to 1801
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   full_title         1802 non-null   object
 1   society_name       896 non-null    object
 2   rent               1802 non-null   object
 3   area_sqft          1802 non-null   int64
 4   furnishing         445 non-null    object
 5   apartment_type     1802 non-null   object
 6   preferred_tenants  1802 non-null   object
 7   link               1802 non-null   object
dtypes: int64(1), object(7)
memory usage: 112.8+ KB

In [33]:
import re
extraction_patterns = [
    r'Sector\s?\d+[A-Za-z]?',   # Matches "Sector 10", "Sector 16B"
    r'Gaur City\s?\d*',         # Matches "Gaur City 1", "Gaur City 2"
    r'Noida Extension',
    r'Greater Noida West',
    r'Tech Zone\s?[IV]*',       # Matches "Tech Zone IV"
    r'Knowledge Park\s?[IV]*',
    r'Ecotech\s?[IV]*',
    r'Surajpur',
    r'\bOmicron\s?[IV]*\b',     # Matches "Omicron I", "Omicron II"
    r'\bDelta\s?[IV]*\b',
    r'\bAlpha\s?[IV]*\b',
    r'\bBeta\s?[IV]*\b',
    r'\bGamma\s?[IV]*\b',
    r'\bZeta\s?[IV]*\b',
    r'\bEta\s?[IV]*\b',
    r'\bMu\s?[IV]*\b',
    r'\bChi\s?[IV]*\b',
    r'\bPi\s?[IV]*\b',
    r'\bOmega\s?[IV]*\b',
    r'\bPhi\s?[IV]*\b',
    r'\bSigma\s?[IV]*\b',
    r'\bRho\b',
    r'\bTheta\b',
    r'\bIota\b',
    r'\bKappa\b',
    r'\bLambda\b',
    r'\bNu\b',
    r'\bXi\b',
    r'\bTau\b',
    r'\bUpsilon\b',
    r'\bPsi\b',
    r'Greater Noida'            # Generic fallback
]

# 3. Extraction Function
def extract_locality(title):
    if not isinstance(title, str):
        return None
    
    # Iterate through patterns and return the first match found
    for pattern in extraction_patterns:
        match = re.search(pattern, title, re.IGNORECASE)
        if match:
            return match.group(0).strip()
    return None

# 4. Apply the function to create the new column
print("Extracting localities...")
df['Locality'] = df['full_title'].apply(extract_locality)

# 5. Check results
filled_count = df['Locality'].notnull().sum()
print(f" Successfully filled {filled_count} rows with locality information.")
print(df[['full_title', 'Locality']].head(10))

Extracting localities...
 Successfully filled 1103 rows with locality information.
                                          full_title   Locality
0  2 BHK Apartment In Arihant Abode for Rent  In ...  Sector 10
1  2 BHK Apartment In Nimbus Express Park View 2 ...      Chi V
2  2 BHK Apartment In Panchsheel Greens, Sector 1...  Sector 16
3  2 BHK Apartment In Ace Divino for Rent  In Sec...   Sector 1
4  1 BHK Apartment In Supertech Czar for Rent  In...  Omicron I
5  2 BHK Flat In Saviour Greenarch for Rent  In E...       None
6    3 BHK Flat In 7th Avanue for Rent  In  Sector 4   Sector 4
7  1 RK Apartment In Ska Metro Ville for Rent  In...     Eta Ii
8  3 BHK Apartment In Golf Gardenia  for Rent  In...   Alpha Ii
9  3 BHK Apartment In Ansal Golf Link 1 for Rent ...       None

In [34]:
df.head()

,full_title,society_name,rent,area_sqft,furnishing,apartment_type,preferred_tenants,link,Locality
0,2 BHK Apartment In Arihant Abode for Rent In ...,Arihant Abode,24000,1055,Fully Furnished,2 BHK,"Female, Family",https://www.nobroker.in/property/2-bhk-apartme...,Sector 10
1,2 BHK Apartment In Nimbus Express Park View 2 ...,Nimbus Express Park View 2,31000,1114,Fully Furnished,2 BHK,"Female, Family, Company",https://www.nobroker.in/property/2-bhk-apartme...,Chi V
2,"2 BHK Apartment In Panchsheel Greens, Sector 1...","Panchsheel Greens, Sector 16 B",20000,975,Fully Furnished,2 BHK,Male,https://www.nobroker.in/property/2-bhk-apartme...,Sector 16
3,2 BHK Apartment In Ace Divino for Rent In Sec...,Supertech Eco Village22 ApartmentsView,26000,1000,Fully Furnished,2 BHK,Male,https://www.nobroker.in/property/2-bhk-apartme...,Sector 1
4,1 BHK Apartment In Supertech Czar for Rent In...,supertech czar,16000,535,Fully Furnished,1 BHK,Male,https://www.nobroker.in/property/1-bhk-apartme...,Omicron I

In [35]:
df.dropna(subset=["Locality" , "society_name"], inplace=True)
df = df.drop('furnishing', axis=1)

In [36]:
print("----"*2,"Unique Localities","-------------------------------"*2)
print(df["Locality"].unique())
print("----"*2,"Shape","-------------------------------"*2)
print(df.shape)
print("----"*2,"NUll Values","-------------------------------"*2)
print(df.isnull().sum())

-------- Unique Localities --------------------------------------------------------------
['Sector 10' 'Chi V' 'Sector 16' 'Sector 1' 'Omicron I' 'Eta Ii'
 'Alpha Ii' 'Surajpur' 'Sector 16b' 'Pi I' 'Zeta I' 'Sector 4'
 'Tech Zone Iv' 'Sector 2' 'Omicron Iii' 'Eta' 'Greater Noida'
 'Gaur City 2' 'Noida Extension' 'Pi' 'Tech Zone' 'Omicron' 'Sector 17'
 'Sector 118' 'Sector 22d' 'Sector 121' 'Sector 12' 'Sector 25' 'Omega'
 'Gaur City' 'Sector 20' 'Omega I' 'Omega Ii' 'Chi' 'Knowledge Park V'
 'Chi Iv' 'Sector 16c' 'Gamma Ii' 'Chi Iii' 'Knowledge Park Iv'
 'Sector 63' 'Knowledge Park I' 'Zeta' 'Sector 150' 'Sector 19'
 'Sector 17a' 'Sector 73' 'Delta I' 'Knowledge Park' 'Sector 22' 'eta'
 'Sector10' 'Omega Iv' 'Mu' 'Gaur City 1' 'Sector 3' 'Gaur City 7'
 'Beta I' 'Greater Noida West' 'Phi Ii' 'Chi Ii' 'Sector22d' 'Sector 120'
 'Sigma' 'Beta' 'Sector 27']
-------- Shape --------------------------------------------------------------
(581, 8)
-------- NUll Values --------------------------------------------------------------
full_title           0
society_name         0
rent                 0
area_sqft            0
apartment_type       0
preferred_tenants    0
link                 0
Locality             0
dtype: int64

In [37]:
df['rent'] = df['rent'].astype(int)
df['rent'] = df['rent'].astype(int)

In [38]:
import re

# Function to extract digits and convert to int
def clean_bhk(val):
    match = re.search(r'\d+', str(val))
    return int(match.group()) if match else None

# Apply transformation
df['apartment_type'] = df['apartment_type'].apply(clean_bhk)

# Save the final result
df.to_csv('D:\personal Projects\Agentic AI\Reaestate Agent 3\Data\Pre-processed/nobroker_numeric_bhk.csv', index=False)

In [39]:
print(df.info())
print("------"*5)
print(df["apartment_type"].unique())

<class 'pandas.core.frame.DataFrame'>
Index: 581 entries, 0 to 1800
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   full_title         581 non-null    object
 1   society_name       581 non-null    object
 2   rent               581 non-null    int32
 3   area_sqft          581 non-null    int64
 4   apartment_type     581 non-null    int64
 5   preferred_tenants  581 non-null    object
 6   link               581 non-null    object
 7   Locality           581 non-null    object
dtypes: int32(1), int64(2), object(5)
memory usage: 38.6+ KB
None
------------------------------
[2 1 3 4]

In [40]:
df.head()

,full_title,society_name,rent,area_sqft,apartment_type,preferred_tenants,link,Locality
0,2 BHK Apartment In Arihant Abode for Rent In ...,Arihant Abode,24000,1055,2,"Female, Family",https://www.nobroker.in/property/2-bhk-apartme...,Sector 10
1,2 BHK Apartment In Nimbus Express Park View 2 ...,Nimbus Express Park View 2,31000,1114,2,"Female, Family, Company",https://www.nobroker.in/property/2-bhk-apartme...,Chi V
2,"2 BHK Apartment In Panchsheel Greens, Sector 1...","Panchsheel Greens, Sector 16 B",20000,975,2,Male,https://www.nobroker.in/property/2-bhk-apartme...,Sector 16
3,2 BHK Apartment In Ace Divino for Rent In Sec...,Supertech Eco Village22 ApartmentsView,26000,1000,2,Male,https://www.nobroker.in/property/2-bhk-apartme...,Sector 1
4,1 BHK Apartment In Supertech Czar for Rent In...,supertech czar,16000,535,1,Male,https://www.nobroker.in/property/1-bhk-apartme...,Omicron I

# Saving Data to SQL Lite Database

In [41]:
import sqlite3
# Create connection (this will create a file if it doesn't exist)
conn = sqlite3.connect(r"D:\personal Projects\Agentic AI\Reaestate Agent 3\Data\Database\nobroker.db")

# Store dataframe into SQLite
df.to_sql("nobroker_cleaned", conn, if_exists="replace", index=False)

# Close connection
conn.close()

In [42]:
conn = sqlite3.connect(r"D:\personal Projects\Agentic AI\Reaestate Agent 3\Data\Database\nobroker.db")

query = "SELECT * FROM nobroker_cleaned LIMIT 5"
df_check = pd.read_sql(query, conn)

print(df_check)

conn.close()

                                          full_title  \
0  2 BHK Apartment In Arihant Abode for Rent  In ...
1  2 BHK Apartment In Nimbus Express Park View 2 ...
2  2 BHK Apartment In Panchsheel Greens, Sector 1...
3  2 BHK Apartment In Ace Divino for Rent  In Sec...
4  1 BHK Apartment In Supertech Czar for Rent  In...

                             society_name   rent  area_sqft  apartment_type  \
0                           Arihant Abode  24000       1055               2
1              Nimbus Express Park View 2  31000       1114               2
2          Panchsheel Greens, Sector 16 B  20000        975               2
3  Supertech Eco Village22 ApartmentsView  26000       1000               2
4                          supertech czar  16000        535               1

         preferred_tenants                                               link  \
0           Female, Family  https://www.nobroker.in/property/2-bhk-apartme...
1  Female, Family, Company  https://www.nobroker.in/property/2-bhk-apartme...
2                     Male  https://www.nobroker.in/property/2-bhk-apartme...
3                     Male  https://www.nobroker.in/property/2-bhk-apartme...
4                     Male  https://www.nobroker.in/property/1-bhk-apartme...

    Locality
0  Sector 10
1      Chi V
2  Sector 16
3   Sector 1
4  Omicron I

# Tools

In [43]:
import os
import requests
from typing import Optional


class AzureMapsTools:
    BASE_URL = "https://atlas.microsoft.com/search/fuzzy/json"
    API_VERSION = "1.0"

    def __init__(self):
        self.session = requests.Session()

  
    # Internal Request Handler
   
    def _make_request(self, params: dict) -> dict:
        api_key = os.getenv("AZURE_MAPS_KEY")

        if not api_key:
            raise ValueError("Azure Maps API key not found in environment variables.")

        params.update({
            "api-version": self.API_VERSION,
            "subscription-key": api_key
        })

        response = self.session.get(
            self.BASE_URL,
            params=params,
            timeout=10
        )
        response.raise_for_status()
        return response.json()

    # Get Coordinates
  
    def _get_coordinates(self, society_name: str) -> Optional[tuple]:
        search_query = (
            society_name
            if "Greater Noida" in society_name
            else f"{society_name}, Greater Noida"
        )

        data = self._make_request({
            "query": search_query,
            "countrySet": "IN",
            "limit": 1
        })

        results = data.get("results")
        if not results:
            return None

        pos = results[0]["position"]
        return pos["lat"], pos["lon"]


    # Public Tool Method

    def find_nearby_amenity(
        self,
        society_name: str,
        amenity_type: str,
        radius: int = 5000,
        limit: int = 10
    ) -> str:

        try:
            coords = self._get_coordinates(society_name)
            if not coords:
                return f"Location not found for '{society_name}'."

            lat, lon = coords

            data = self._make_request({
                "query": amenity_type,
                "lat": lat,
                "lon": lon,
                "radius": radius,
                "limit": limit
            })

            results = data.get("results", [])
            if not results:
                return f"No {amenity_type} found within {radius}m of {society_name}."

            filtered = [
                f"- {item.get('poi', {}).get('name', 'Unknown')} "
                f"({int(item.get('dist', 0))}m)"
                for item in results
                if "Sector" not in item.get("poi", {}).get("name", "")
            ]

            return (
                f"Nearby {amenity_type}s near '{society_name}':\n"
                + "\n".join(filtered)
            )

        except requests.RequestException as e:
            return f"API request failed: {str(e)}"
        except Exception as e:
            return f"Unexpected error: {str(e)}"



# Usage
azure_maps = AzureMapsTools()

print("Setup Complete.")
print(azure_maps.find_nearby_amenity("Ace City", "School"))

Setup Complete.
Nearby Schools near 'Ace City':
- Sunfort (633m)
- Maple Bear (701m)
- Uma Maheshwari Public School (776m)
- Primary School Aminabad (780m)
- Delhi World Public School (1240m)
- Government Primary School (1398m)
- Government Primary School (1571m)
- Junior Highschool Jalpura (1598m)
- Balwir Uday Public School (1790m)
- Government Purva Madyamik Vidyalaya (1902m)

In [44]:
import sqlite3
import pandas as pd

class MarketAnalysisTools:
    def __init__(self, db_path):
        self.db_path = db_path

    def get_market_context(self, locality: str):
        """Fetches property data for a locality to calculate medians."""
        conn = sqlite3.connect(self.db_path)
        # Fetch raw data to calculate the median in pandas (SQL doesn't have a native MEDIAN function)
        query = f"""
            SELECT rent, area_sqft
            FROM nobroker_cleaned 
            WHERE Locality = '{locality}'
        """
        df = pd.read_sql_query(query, conn)
        conn.close()
        
        if df.empty:
            return None
            
        # Calculate price per sqft for every row to find the true middle ground
        df['price_per_sqft'] = df['rent'] / df['area_sqft']
        
        return {
            "locality": locality,
            "median_rent_per_sqft": df['price_per_sqft'].median(),
            "sample_size": len(df)
        }

    def evaluate_deal(self, rent: int, area_sqft: int, locality: str) -> str:
        """Compares a specific property to the localized market median and outputs negotiation advice."""
        market_data = self.get_market_context(locality)
        
        if not market_data:
            return f"No market data available for {locality} to evaluate this deal."
        
        prop_price_per_sqft = rent / area_sqft
        market_median = market_data['median_rent_per_sqft']
        
        # Calculate % difference from market median
        diff = ((prop_price_per_sqft - market_median) / market_median) * 100
        
        # Calculate what the rent SHOULD be based on the median
        fair_rent = market_median * area_sqft
        
        # Helper function to format numbers like 16500 into '16.5k'
        def to_k(amount):
            return f"₹{amount/1000:.1f}k".replace('.0k', 'k')
            
        # Create a realistic negotiation range (e.g., 5% below fair rent to 2% above)
        range_low = to_k(fair_rent * 0.95)
        range_high = to_k(fair_rent * 1.02)
        asking_rent_k = to_k(rent)

        # Format the exact output string for the AI to read
        if diff > 5.0:
            return f"Property is {diff:.1f}% overpriced vs locality median. Recommended negotiation range {range_low}–{range_high}."
        elif diff < -5.0:
            return f"Property is {abs(diff):.1f}% underpriced vs locality median. Excellent deal! Recommend locking it in near the asking price of {asking_rent_k}."
        else:
            return f"Property is priced at Fair Market Value ({abs(diff):.1f}% variance vs median). Recommended negotiation range {range_low}–{range_high}."

# --- Usage Test ---
analysis = MarketAnalysisTools(r"D:\personal Projects\Agentic AI\Reaestate Agent 3\Data\Database\nobroker.db")
print(analysis.evaluate_deal(24000, 1055, "Sector 10"))

Property is priced at Fair Market Value (0.8% variance vs median). Recommended negotiation range ₹22.6k–₹24.3k.

# Agent

In [45]:
import os
import uuid
from agno.agent import Agent
from agno.models.azure import AzureOpenAI
from agno.db.sqlite import SqliteDb
from agno.memory import MemoryManager
from rich.pretty import pprint

In [46]:
# Importing the SQL tool to allow querying your specific database
from agno.tools.sql import SQLTools

# 1. Define your Database Path
db_path = r"D:\personal Projects\Agentic AI\Reaestate Agent 3\Data\Database\nobroker.db"

# 2. Setup the unified SQLite Database component
db = SqliteDb(db_file=db_path)

# 3. Setup the Central Memory Manager
memory_manager = MemoryManager(db=db)

In [49]:
# 4. Initialize the Agent
agent = Agent(
    model=AzureOpenAI(
        id="gpt-4.1-mini-2", # Ensure this matches your Azure deployment ID exactly
        api_version="2024-08-01-preview",
        temperature=0,
    ),
    # Link the SQLite database for session history (Short-Term Memory)
    db=db,
    # Link the Memory Manager for user facts (Long-Term Memory)
    memory_manager=memory_manager,
    
    # Active learning for user preferences
    enable_user_memories=True, 
    
    add_history_to_context=True,
    num_history_runs=3,
    
    # 5. Attach your specific Tools
    tools=[
        azure_maps.find_nearby_amenity,
        analysis.evaluate_deal,
        # Adding the SQL Tool so the agent can query your cleaned housing data
        SQLTools(db_url=f"sqlite:///{db_path}")
    ],
    instructions=[
    "You are a top-tier Real Estate Broker for Greater Noida. You must clearly distinguish between finding 'Housing Inventory', evaluating 'Market Deals', and finding 'Neighborhood Amenities'.",

    "### STEP 0: CLASSIFY USER INTENT",
    "Before calling ANY tool, determine the user's goal:",
    "- **GOAL A: FIND HOUSING** -> User wants flats, apartments, or property options. (Keywords: 'rent', 'flat', 'BHK', 'budget').",
    "- **GOAL B: EVALUATE DEAL** -> User wants to know if a rent price is fair. (Keywords: 'overpriced', 'good deal', 'fair price').",
    "- **GOAL C: FIND AMENITIES** -> User wants nearby facilities. (Keywords: 'school', 'hospital', 'mall', 'market').",

    "### STEP 1: TOOL USAGE MAP (STRICT)",
    "1. **Tool: `SQLTools` (Database)**",
    "   - **Function**: Queries the `nobroker_cleaned` table in the SQLite database.",
    "   - **When to use**: ALWAYS use this first to find flats, rents, or confirm a society's location.",
    "   - **CRITICAL SCHEMA**: `apartment_type` (INTEGER) is used for BHK. `society_name` (TEXT) is the building name. `Locality` (TEXT) is the sector. `rent` (INTEGER). `area_sqft` (INTEGER).",
    
    "2. **Tool: `azure_maps.find_nearby_amenity`**",
    "   - **When to use**: ONLY for GOAL C (Amenities). Finds landmarks on a map.",
    "   - **Input Rules**: `amenity_type` MUST be singular (e.g., 'School', not 'Schools'). `society_name` should be a clean string.",
    
    "3. **Tool: `analysis.evaluate_deal`**",
    "   - **When to use**: ONLY for GOAL B (Evaluate Deal). Compares a property against the sector median and provides a negotiation strategy.",
    "   - **Input Rules**: Requires `rent` (int), `area_sqft` (int), and `locality` (str).",

    "### STEP 2: EXECUTION WORKFLOWS",
    "- **Locality Translation Rule (CRITICAL)**:",
    "   - **Problem**: Users type conversational names like 'chi 5', 'sector pi 2', or 'tech zone 4'.",
    "   - **Database Reality**: The database uses Roman numerals and often omits the word 'sector' (e.g., 'Chi V', 'Pi II', 'Tech Zone IV').",
    "   - **Solution**: You MUST translate Arabic numerals (1, 2, 3, 4, 5) to Roman numerals (I, II, III, IV, V) before querying.",
    "   - **Pattern**: NEVER use strict equality for these. Use wildcards. For 'chi 5', write `WHERE Locality LIKE '%Chi%V%'`. For 'pi 2', write `WHERE Locality LIKE '%Pi%II%'`.",

    "- **SQL Queries ('Noisy Data' Rule)**:",
    "   - **Problem**: Database names can be messy (e.g., 'Godrej Golf Links Crest').",
    "   - **Solution**: NEVER search for exact full strings. Use `LIKE` with split keywords.",
    "   - **Pattern**: `SELECT ... WHERE society_name LIKE '%Godrej%' AND society_name LIKE '%Crest%'`.",
    "   - **BHK Rule**: If the user wants a 2 BHK, ALWAYS write `WHERE apartment_type = 2`.",

    "- **Workflow for Amenities (Goal C)**:",
    "   1. Run SQL to confirm the `society_name` exists.",
    "   2. Call `find_nearby_amenity` using the confirmed society name.",

    "- **Workflow for Market Evaluation (Goal B)**:",
    "   1. Use SQL to find the specific property the user is asking about to get its rent, area, and locality.",
    "   2. Pass those exact numbers into the `evaluate_deal` tool.", 

    "### STEP 3: MEMORY & PERSONALIZATION",
    "- Always check user memories for previously stated preferences (Budget, Locality, BHK).",
    "- Automatically apply remembered constraints to your SQL queries (e.g., if memory says 'Budget is 25000', add `WHERE rent <= 25000`) unless the user explicitly changes it.",

    "### STEP 4: RESPONSE FORMAT",
    "- **Housing**: Use a Markdown Table: `| Title | Society | Locality | BHK | Rent | Area | Link |`",
    "- **Amenities**: Use bullet points with specific names and distances.",
    "- **Deals**: Output the EXACT negotiation string returned by the `evaluate_deal` tool. Format this string in **bold** (e.g., **Property is 12.3% overpriced vs locality median. Recommended negotiation range ₹16k–17k.**)."
],
    # REMOVED: show_tool_calls=True
    markdown=True,
    debug_mode=True
)

In [50]:
# --- Interactive Chat Loop ---

# Generate a unique user ID for this specific client
client_id = f"client_{str(uuid.uuid4())[:8]}"

print(f"--- Starting Interactive Session for {client_id} ---")
print("Type 'exit' or 'quit' to end the chat.")
print("Type 'memory' at any time to see what the agent has learned about you.\n")

while True:
    # 1. Capture your input from the Jupyter text box
    user_input = input("User: ")
    
    # Print it to the screen so you have a visual log of what you asked
    print(f"User: {user_input}")
    
    # 2. Handle special commands
    if user_input.lower() in ['exit', 'quit', 'bye']:
        print("\nAgent: Goodbye! Closing the session.")
        
        # Optional: Print the final memory dump before leaving
        print("\n--- Final Central Memory Dump ---")
        memories = agent.memory_manager.get_user_memories(user_id=client_id) if hasattr(agent.memory_manager, 'get_user_memories') else "Check database directly for memories"
        pprint(memories)
        break
        
    if user_input.lower() == 'memory':
        print("\n--- Current Central Memory Dump ---")
        memories = agent.memory_manager.get_user_memories(user_id=client_id) if hasattr(agent.memory_manager, 'get_user_memories') else "Check database directly for memories"
        pprint(memories)
        print("-----------------------------------\n")
        continue

    # 3. Process the input through the Agent
    # We use .run() to ensure Jupyter captures the text properly
    response = agent.run(user_input, user_id=client_id)
    
    # 4. Print the agent's response
    print(f"Agent:\n{response.content}\n")

--- Starting Interactive Session for client_7c0fcfc6 ---
Type 'exit' or 'quit' to end the chat.
Type 'memory' at any time to see what the agent has learned about you.

User: shoe me property in chi 5

DEBUG ****** Agent ID: 13c9fb2c-dbe4-4bd9-98a4-241788566c65 ******

DEBUG Reading AgentSession: 6bc51937-fc0d-450d-b3a6-ef31c32678ad

DEBUG Creating new AgentSession: 6bc51937-fc0d-450d-b3a6-ef31c32678ad

DEBUG Processing tools for model

DEBUG Added tool find_nearby_amenity

DEBUG Added tool evaluate_deal

DEBUG Added tool list_tables from sql_tools

DEBUG Added tool describe_table from sql_tools

DEBUG Added tool run_sql_query from sql_tools

DEBUG ** Agent Run Start: b1c573fc-c7ae-47c5-873f-dd549a909dcc ***

DEBUG Starting memory creation in background thread.

DEBUG Managing user memories

DEBUG ------------------- Azure Response Start -------------------

Agent:
Here are some properties available in Chi 5:

| Society                  | Locality | BHK | Rent  | Area (sqft) |
|--------------------------|----------|-----|-------|-------------|
| Nimbus Express Park View 2 | Chi V    | 2   | ₹31,000 | 1114        |
| Purvanchal Royal City     | Chi V    | 3   | ₹35,000 | 1735        |
| Proview Technocity Apartments | Chi V    | 2   | ₹9,000  | 1200        |
| Proview Technocity Apartments | Chi V    | 3   | ₹32,000 | 1492        |
| Proview Technocity Apartments | Chi V    | 3   | ₹35,000 | 1300        |
| Purvanchal Royal City     | Chi V    | 3   | ₹40,000 | 1725        |
| Gaur Yamuna City          | Chi V    | 2   | ₹16,500 | 900         |
| Proview Technocity Apartments | Chi V    | 3   | ₹30,000 | 1201        |
| Purvanchal Royal City     | Chi V    | 3   | ₹37,000 | 1825        |

If you want details or links for any specific property or want to filter by BHK or budget, please let me know!

User: show me hospitals nearby Nimbus Express Park View 2

DEBUG ****** Agent ID: 13c9fb2c-dbe4-4bd9-98a4-241788566c65 ******

DEBUG Reading AgentSession: 6bc51937-fc0d-450d-b3a6-ef31c32678ad

DEBUG Processing tools for model

DEBUG Added tool find_nearby_amenity

DEBUG Added tool evaluate_deal

DEBUG Added tool list_tables from sql_tools

DEBUG Added tool describe_table from sql_tools

DEBUG Added tool run_sql_query from sql_tools

DEBUG Getting messages from previous runs: 4

DEBUG Adding 4 messages from history

DEBUG ** Agent Run Start: 7043fd72-2524-4e09-9ef8-6d069a9cb1bc ***

DEBUG Starting memory creation in background thread.

DEBUG ------------------- Azure Response Start -------------------

DEBUG Managing user memories

DEBUG ------------------ Model: gpt-4.1-mini-2 -------------------

Agent:
Nearby Hospitals near Nimbus Express Park View 2:
- Prayag Hospital (2046m)
- Artho Child Care Clinic (838m)
- Riyan Medical Centre (1102m)
- Aarogya Sri Hospital (1131m)
- The Aminent Dharmarth Free Ayurveda Hospital (1230m)

User: is rent of Nimbus Express Park View 2 fair?

DEBUG ****** Agent ID: 13c9fb2c-dbe4-4bd9-98a4-241788566c65 ******

DEBUG Reading AgentSession: 6bc51937-fc0d-450d-b3a6-ef31c32678ad

DEBUG Processing tools for model

DEBUG Added tool find_nearby_amenity

DEBUG Added tool evaluate_deal

DEBUG Added tool list_tables from sql_tools

DEBUG Added tool describe_table from sql_tools

DEBUG Added tool run_sql_query from sql_tools

DEBUG Getting messages from previous runs: 10

DEBUG Adding 10 messages from history

DEBUG ** Agent Run Start: 770af7f1-d7c5-48c2-855e-aa09a1c22f56 ***

DEBUG Starting memory creation in background thread.

DEBUG ------------------- Azure Response Start -------------------

DEBUG Managing user memories

DEBUG ------------------ Model: gpt-4.1-mini-2 -------------------

Agent:
**Property is 29.7% overpriced vs locality median. Recommended negotiation range ₹22.7k–₹24.4k.**

User: exit

Agent: Goodbye! Closing the session.

--- Final Central Memory Dump ---

[]